### ISSUE TITLE
Backfill MetaDB with LIMs database

### ISSUE THREAD

**Issue by n1zea144** [mskcc/cmo-metadb#11]
Get some example requests to simulate the 3 cases:

1. tumor and normal paired in same request (08944_B)
2. tumor in request but normal from previous request 
3. pooled normals (just include in request)

Relevant information from meeting with David and Lisa:  https://github.com/mskcc/cmo-metadb/issues/70#issuecomment-764925088

**Comment by ao508** [comment]
Follow up with Lisa

**Comment by ao508** [comment]
Confirm that the sample missing cmo information is linked back to its cmo data  (XXXX_BZ_22)

**Comment by divyamadala30** [comment]
08944_B, 2 normals and 2 tumors in same request.
08039_BZ. IMPACT468. 9 tumor samples. 8 normals from same request. 1 normal from different request (08039_CC).
05604_Z. IMPACT468. 4 tumor samples against pooled normals.
09483_O, one tumor sample that matched with a normal from (09483_B).
