### ISSUE TITLE
Identify exceptions that can occur during publishing failures

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#125]
Should different exceptions be handled differently?

For now can just catch general "exception" and  just write to a file that this (date, topic, message) failed to publish. Can decide on how we would automate the recovery effort later. 

resource:
https://docs.nats.io/developing-with-nats/events/

Goal: We will be introducing our own implementation of an `ErrorListener`
see reference docs here https://docs.nats.io/developing-with-nats/events/slow

**Comment by divyamadala30** [comment]
**cmo-messaging-java**
- Slow Consumer
    -inactive client forces NATS server to close the connection
    -Proposed solution: [ErrorListener](https://docs.nats.io/developing-with-nats/events/events) prints out the number of messages dropped with the connection
- Failed publish exception
    -message failed to be published to a certain topic
    -Proposed solution: Log the date, topic, and message that failed to publish

- Client ID already in use
    -Multiple clients cannot use the same client ID
    -Proposed solution: Log/print a more specific message including the 
- More exceptions (timeout, server disconnect...)
    -Proposed solution: Log/print the exception with more details

**cmo-metadb**
- Catch persistence failures
    -Incorrect cypher query, Neo4J connection failure
    -Proposed solution: 

**cmo-metadb-sample-publisher**
- LimsRest connection failure
    -Proposed solution:
