### ISSUE TITLE
Create WebService for fetching CMO_NEW_REQUEST json

### ISSUE THREAD

**Issue by n1zea144** [mskcc/cmo-metadb#140]
We would like a web service endpoint to fetch CMO_NEW_REQUEST json out of graph database.  This can be used by (at least) the limsrest consistency checking tool prior to rollout of MetaDB server.

Might be useful for reference:

https://github.com/genome-nexus/genome-nexus/blob/master/web/src/main/java/org/cbioportal/genome_nexus/web/InfoController.java

Requirements:
- [ ] add web module
- [ ] controller will need an autowired request service
- [ ] add controller for fetching metadb request JSON given a request id

```
    @ApiOperation(value = "short description",
        nickname = "fetchRequestJsonGET")
    @RequestMapping(value = "/request",
        method = RequestMethod.GET,
        produces = "application/json")
    @ResponseBody
    public MetaDbRequest fetchRequestJsonGET()
    {
        return (instance of MetaDbRequest);
    }
```

**Comment by divyamadala30** [comment]
PR: https://github.com/mskcc/cmo-metadb/pull/145
