### ISSUE TITLE
[UNIT TEST] Create WebService for fetching CMO_NEW_REQUEST json

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#146]
Related card / issue with the programming effort: https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/cmo-metadb/140

**Comment by divyamadala30** [comment]
- POST method should return Map<String, Map<String, Object>> (example [here)](https://github.com/genome-nexus/genome-nexus/blob/master/web/src/test/java/org/cbioportal/genome_nexus/web/AnnotationIntegrationTest.java#L48) where the key
is the request id and the value is the Map<String, Object> representing the metadb request json
- The POST response should return the data for each given request id in the order that they were received. I believe the name of this type of class is something like "LinkedHashMap" - you may have to double check.
- If a request ID in a POST response is invalid (it does not exist in the graphdb) then return a null but add the request id in the returned map
- mock data loaded from one of the the json files linked above and check that it's deserialized correctly (fields match the expected values)

MOCK DATA -> https://github.com/mskcc/cmo-metadb/tree/master/test/data

Example that uses mockito to mock data -> https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/annotator/src/test/java/org/cbioportal/annotator/MockGenomeNexusImpl.java
