### ISSUE TITLE
Review Igo Request JSON v.  MetaDB Request JSON

### ISSUE THREAD

**Issue by n1zea144** [mskcc/cmo-metadb#157]
- make sure outgoing models match expected model, and that metadb models are in sync as well and investigate discrepancies reported below

The following differences were noticed between Request JSON coming from LimsRest and Request JSON coming from MetaDB MVC Controller (some may be ok, but we should review)

Properties introduced by MetaDB in getRequestSamples JSON

id
idSource
projectId
sampleManifestList (called samples in LimsRest)

Properties introduced by MetaDB in getSampleManifast

id
ancestorSample
creationTime
creationDate
cmoSampleId
fastqPath
mrn
parentTumorType
principalInvestigator
recipe
requestId
sampleStatus
sampleType
tissueSource
tumorType
numFastQs (part of "libraries" component) <-- this field  was recently deployed to tango but will not be going to production

**Comment by ao508** [comment]
Let's match JSON/jackson annotations that the LimsRest has with our own models:

- GetRequestSamples, if the fields in their models have the @JsonInclude then add it to the corresponding field(s) in our IgoRequest class as well https://github.com/mskcc/LimsRest/blob/master/src/main/java/org/mskcc/limsrest/service/GetRequestSamplesTask.java
