### ISSUE TITLE
Fix Swagger page configuration for MetaDB web controller

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#163]
Example model/json isn't being shown for either the GET or POST

Consider introducing a web-specific model of the packaged json that we will be returning in the REST service and publishing for downstream apps/clients. 

Add endpoint for fetching a `requestJsonString`

**Comment by ao508** [comment]
PR https://github.com/mskcc/cmo-metadb/pull/180

**Comment by n1zea144** [comment]
I see patientUUID and sampleUUID on the swagger model.  I also see metaDbRequestId is a UUID by looking at the PublishedMetaDbRequest.java class.  Can we make one name consistent across all entities?

**Comment by ao508** [comment]
In SampleMetadata -> rename sampleUuid and patientUuid to [sample][patient]MetaDbId
