### ISSUE TITLE
Run MetaDbRequestServiceImpl.saveRequest() in a transaction

### ISSUE THREAD

**Issue by n1zea144** [mskcc/cmo-metadb#168]
Setup transactions so that we don't end up with partially built graphs.

Hopefully we can just annotate this method as being transactional....
![image.png](https://images.zenhubusercontent.com/570fd610bf93871ccd99739b/ca7a489d-9667-46cf-b800-fd5bd6229bd4)

otherwise we end up with this:

![image.png](https://images.zenhubusercontent.com/570fd610bf93871ccd99739b/d58b548b-3821-40c6-8928-5bed8054e942)

**Comment by ao508** [comment]
DRAFT PR https://github.com/mskcc/cmo-metadb/pull/182/files

**Comment by ao508** [comment]
This is my current dev branch for this effort https://github.com/ao508/cmo-metadb/tree/transactional-operations

This is still a work in progress
