### ISSUE TITLE
Properly Handle MetaDB Publishing Failures

### ISSUE THREAD

**Issue by n1zea144** [mskcc/cmo-metadb#24]
How to handle when messages are published but NATS server is down. What happens?
What are our procedures for making updates to NATS server, CMO MetaDB app, etc.
Add our own log file to publish failed messages (LIMS), maybe log request id to a specific file and that is shared with some tool, maybe our publisher standalone tool.

**Comment by ao508** [comment]
Started looking into file stores and sql store. These would facilitate recovery if the MetaDB app is down but NATS itself is still running.

**Comment by n1zea144** [comment]
I like the idea of using a store, it is another system to maintain, but maybe unavoidable.   I'm trying to avoid a request-reply/synchronized exchange and does it address the problem?  That is, if the request-reply does not return, don't we still end up in the same situation?  Having said that, a request-reply to check that NATs is running before attempting to publish may make for a clean handling of when NATs is down.
