### ISSUE TITLE
Add check in init-nats-stream-consumers.sh for whether a stream and/or consumer has been set up already

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#247]
I dont think it's an issue if the commands in init-nats-stream-consumers.sh are run regardless of whether there's a check or not but it would be good to confirm. 

If a stream/consumer exists already then what is the exit code? 

Can we do a simple restart of one of the docker-compose components instead of redeploying everything? (nats-jetstream)

**Comment by divyamadala30** [comment]
To restart a specific service using docker-compose:

```docker-compose restart [service-name]```

If new changes were added to the service, use to rebuild and restart the service:

```docker-compose up -d [service-name]```
