### ISSUE TITLE
Fix issue with acknowledging messages.

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#283]
We should add a manual acknowledgement for client subscribers. 

Messages are being "published" more than once on NATS JS side of things because they are not being properly acknowledge. 

@divyamadala30 can you expand on this a bit?

PRs:
- https://github.com/mskcc/cmo-messaging-java/pull/34
- https://github.com/mskcc/cmo-metadb/pull/284
- https://github.com/mskcc/cmo-metadb-consistency-checker/pull/26

Will also need to update the messaging lib commit in:

- sample publisher
- cpt gateway
- irt 
- lims rest

**Comment by ao508** [comment]
This issue is more involved than initially anticipated

- This might be useful: [github link](https://github.com/nats-io/nats.java/blob/main/src/examples/java/io/nats/examples/jetstream/NatsJsPushSub.java#L98)


Environment:

- running nats, neo4j locally
- CMO-MetaDB server running outside of docker compose (java -jar ..)
  - subscribed to `METADB.igo-new-request` and publishing to `METADB.consistency-check-new-request`

Gist of the issue: message is not being acknowledged... 
- manual ack added to JSGatewayImpl (in `onMessage()` method)  
- manual ack also added to MessageHandlingServiceImpl in both the Consistency Checker app and CMO MetaDB app. 

Initial thoughts: are these messages even getting acknowledged when invoking the ack method on the `Message` object? [see my modified messaging library](https://github.com/ao508/cmo-messaging-java/blob/manual-ack/src/main/java/org/mskcc/cmo/messaging/impl/JSGatewayImpl.java#L178)

NEXT STEPS:
- Let's just run the CMO metadb server for now and not worry about the consistency checker since MetaDB has a much simpler set up.
- Run publisher w/publish to topic `METADB.igo-new-request`. 

--> Try to narrow down why the subscriber is seeing the same message multiple times if it's only being published by the publisher once?

**Comment by divyamadala30** [comment]
Possible changes to try to prevent duplication of messages:

- Increase the ack wait time from 30 seconds to 10 minutes.

- Add an id to the header of the message being published. More details [here](https://github.com/nats-io/jetstream#message-deduplication)

- use `--dupe-window` (set to 2 minutes) to look out for duplicates
