### ISSUE TITLE
Add request-reply functionality to cmo-messaging-java

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#311]

**Comment by ao508** [comment]
something funky is definitely going on with the request-reply implementation. 

It seems that when you attempt to do a request-reply the message is being received on the request reply topic multiple times. This reminds me a bit of when we were running into that duplicate message issue where the received message wasn't being acknowledged properly

**Comment by divyamadala30** [comment]
PR: https://github.com/mskcc/cmo-messaging-java/pull/38
