### ISSUE TITLE
stream configuration updates: init script, application properties, & server configuration

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#322]
@divyamadala30 can you add more details here?

**Comment by divyamadala30** [comment]
Stream will have subject: METADB.>

Services to be updated:

- [ ] **cmo-metadb**: filterSubject = METADB.server.>

- [ ] **cmo-sample-validator**: filterSubject = METADB.validator.*

- [ ] **sample-id-generator**: filterSubject = METADB.generator.*

- [ ] **limsrest** - not sure if we need this: filterSubject = METADB.lims.*

- [ ] **consistency-checker**: filterSubject = METADB.server.consistency-checker.* 

- [ ] **cpt-gateway**: filterSubject = METADB.cpt-gateway.*

- [ ] **jetstream.conf**: update the subjects

- [ ] **init script**: update filterSubjects

New Subjects:

- METADB.igo-new-request --> METADB.server.consistency-checker.igo-new-request
- METADB.consistency-check-new-request --> METADB.server.consistency-checker.processed-request?
- METADB.cmo-new-request --> METADB.cpt-gateway.cmo-new-request
- METADB.igo-cmo-label-generator -->METADB.generator.cmo-label
- METADB.request-filter --> METADB.validator.request-filter

**Comment by ao508** [comment]
@divyamadala30 The consistency checker having `METADB.server.consistency-checker.*` instead of just `METADB.consistency-checker.*` is a little confusing to me. 

Is there a reason it should also be under `METADB.server.`?
