### ISSUE TITLE
Capture MetaDB behavior in RFC

### ISSUE THREAD

**Issue by n1zea144** [mskcc/cmo-metadb#331]
We've made decisions over the course of development with regards to certain behaviors of MetaDB, like:

* any duplicate request from LimsRest gets routed to a bucket for qc
* a sample with erroneous data will get removed from the request for qc and not persisted in MetaDB

Done:

Capture these and any other behavior in the MetaDB RFC for transparency:
https://docs.google.com/document/d/1s7bRDQ-fBkiwZhi1KxrX483iM5uzacpupfwif3wg8mo/edit#heading=h.ja8ro0sd8103

Similarly, capture any choices made during the development of the CMO sample label generator here:
https://docs.google.com/document/d/1s7bRDQ-fBkiwZhi1KxrX483iM5uzacpupfwif3wg8mo/edit#heading=h.v1kxbq3eww15

**Comment by divyamadala30** [comment]
- any duplicate request from LimsRest gets routed to a bucket for qc
- a sample with erroneous data will get removed from the request for qc by the validator and will not be published to metadb
- Samples with missing fields required to generate CMO SampleId will bot be published to metadb
- If a request with the same id is received multiple times within 2 minutes, only one will be persisted to the graph
- If a request with a existing requestId to received and the request is not a duplicate (as in new sample information), the request node expands by adding the missing sample metadata
- Igo requests go through the cmo sample id generator while non-igo requests skip this step
- MetaDb assigns uuids to uniquely identify nodes
- Once the request is persisted, the consistency checker validates the published json and the json produced from neo4j. If these jsons do not match the criteria, the request jsons are logged to be handled later

**Comment by n1zea144** [comment]
I've moved these bullets to the RFC1 MetaDB (under the two links above) and added some comments.
