### ISSUE TITLE
[metadb server] Add message handler for clinical data integration

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#428]
Add a new message handler that subscribes to the clinical data integration topic from #427 

Message handler will need to communicate with CRDB ID mappings table to get the appropriate CMO patient ID so that the clinical information can be linked to its respective MetaDB canonical sample (or patient) node.

**Comment by divyamadala30** [comment]
Progress made: canonical nodes are saved correctly except for sampleMetadata. This node contains no data.
