### ISSUE TITLE
Add list of aliases in returned SampleMetadata JSON

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#457]
- This will be part of the Universal MetaDB JSON.
- New field name in sample metadata: `sampleAliases` (or maybe just aliases)
- consistency checker will need to know to ignore this field 

**This effort does not require any sort of database/schema migration**

Sample Metadata schema change:
```
{
          . . . 
  'sampleAliases': [
    {
      'namespace': string, 
      'value': string
    },
    {
      'namespace': string, 
      'value': string
    },
          . . . 
  ]
          . . . 
}
```

**Comment by divyamadala30** [comment]
PR(cmo-metadb): https://github.com/mskcc/cmo-metadb/pull/468
PR(commons): https://github.com/mskcc/cmo-metadb-common/pull/13
