### ISSUE TITLE
CMO Label Generator Unit Test - Nucleic Acid Abbreviation and Counter

### ISSUE THREAD

**Issue by n1zea144** [mskcc/cmo-metadb#539]
The CMO Patient Label and Sample Label generation PDF introduced new behavior when the same sample is run on different platforms:

```
Counter: integer value incremented when the source is the same. (eg. if C-123456-T001-d is sequenced on Agilent Exome
and now the investigator wants to use the same sample with IDT, then we should have the sample labled C-123456-T001-
d02). Counter will be a 2 digit integer value range from 01-99 (values less < 10 are filled in with zeros '0' to preserve 2-digit
format). From the time of implementation the first sample for a particular Nucleic Acid get 01. 
```

If its not done already, create a unit test to check this behavior.

**Comment by ao508** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/metadb-scrum-5fcfa28a4ccc1600165347b6/issues/mskcc/cmo-metadb/539?planning-poker) with ZenHub @divyamadala30
