### ISSUE TITLE
Demo LimsRest delivery and integration of NATS publishing to CMO MetaDB

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#69]
**UPDATES**

David successfully deployed our code to tango but we arent receiving the published messages. I've followed up w/HPC to get an update on my access to tango so I can see the logs.

------

Demo a message is published to CMO MetaDB when a request is "Delivered"

Relevant information from meeting with Lisa and David can be found here:  https://github.com/mskcc/cmo-metadb/issues/70#issuecomment-764925088

Estimated time frame to deploy the publisher to production / incorporate our publisher into the logic of the "MarkDelivery" button is approximately 2 weeks from today (01/21/2021).

Cases: 
- 08944_B, 2 normals and 2 tumors in same request.
- 08039_BZ. IMPACT468. 9 tumor samples. 8 normals from same request. 1 normal from different request (08039_CC). 
- 05604_Z. IMPACT468. 4 tumor samples against pooled normals.

**Comment by divyamadala30** [comment]
cases:

05604_Z. IMPACT468. 4 tumor samples against pooled normals. 
08039_BZ. IMPACT468. 9 tumor samples. 8 normals from same request. 1 normal from different request (08039_CC).

**Comment by ao508** [comment]
Need to follow up regarding 403 error on the 08039_BZ and 08039_CC access with PMS and metadb-user/metadb-api  credentials.

**Comment by ao508** [comment]
Update: Waiting for permissions to be fixed for the metadb-user (metadb-api1, metadb-api2) accounts to be given access to these requests. 

Attempts to pull data for requests 08039_BZ and 08039_CC still returning 403 errors with `pms` credentials.

**Comment by ao508** [comment]
Almost able to demonstrate this with the Lims `MarkDelivery` button! Working out some deployment and conflicting log binding issues with David but they might be resolved now. Should know more by the end of the day Tuesday, March 9.
