### ISSUE TITLE
Consistency checker tool for checking LIMS requests on a given date made it into MetaDB

### ISSUE THREAD

**Issue by ao508** [mskcc/cmo-metadb#79]
Standalone tool where you pass a delivery date and fetch the requests that LIMS delivered that date and make sure that MetaDB has those requests in the graphDB. 

See "get request deliveries" LIMS API.

**Comment by n1zea144** [comment]
One possible implementation is to use NATs to feed the information in realtime.  A consistency checker is listening to a single topic, NEW_REQUEST_CONSISTENCY_CHECK published in two locations:

- at the time of IGO_NEW_REQUEST publishing
- at the time of CMO_NEW_REQUEST publishing

the content of the messages is the same content with the possible addition of a consistency check id (if required) used to map the new request messages from both sources inside the consistency checker tool.  The consistency checker can report if the two messages are inconsistent of if one of the pair never arrives.

https://app.lucidchart.com/lucidchart/72b4533d-84f7-439c-8bb9-92b3cfe5e567/view?page=0_0#

![image](https://user-images.githubusercontent.com/366003/109172386-b6080500-7750-11eb-8056-ed53a0c9bee3.png)
