### ISSUE TITLE
MetaDB - SampleService Implementation [neo4j]

### ISSUE THREAD

**Issue by n1zea144** [mskcc/cmo-metadb#8]
We need a SampleService class to go between the messaging handler service and persistence(neo4j) library.  For starters:

Sample saveSample(Sample)
Sample findMatchedNormalSample(Sample) --> should return a list, but most cases it would only be one normal in a list

I think "sample" in this case should be the Java equivalent of what is returned by LIMSRest.getSampleManifest().

The normal and tumor samples should have the same sample class and baitsets.

**Comment by divyamadala30** [comment]
PR: https://github.com/mskcc/cmo-metadb/pull/76/files
