### ISSUE TITLE
Include SampleManifest (shared package) & SampleMetadata (shared package) properties on SampleMetadata (model package)

### ISSUE THREAD

**Issue by n1zea144** [mskcc/cmo-metadb#97]
Modify the EntityScan annotation in MetadbApp.java to include the shared enitity package:
@EntityScan(basePackages = {“org.mskcc.cmo.shared”, “org.mskcc.cmo.metadb.model”})

For this to work, Library (shared package) & Run (shared package) classes need to be modified/annotated with @Id.

**Comment by ao508** [comment]
closing due to change in design
